#!/usr/bin/env php
<?php

/*
  ===============
  minecraft_users
  ===============

  This is munin plugin to monitor the player count on a Minecraft server.
  Install it like any other munin plugin:
  # cp minecraft_users_ /usr/share/munin/plugins/minecraft_users_
  # chmod 755 /usr/share/munin/plugins/minecraft_users_
  # ln -s /usr/share/munin/plugins/minecraft_users_ /etc/munin/plugins/minecraft_users_<hostname>:<port>

  No configuration is necessary because minecraft_users_ is a wildcard plugin.
 */

error_reporting(E_ERROR | E_PARSE);

$plugin_name = $argv[0];
if (preg_match('/minecraft_users_([^[:blank:][:cntrl:]]+)(?::([0-9]+))?$/', $plugin_name, $matches)) {
    $host = $matches[1];
    $port = empty($matches[2]) ? '25565' : $matches[2];
} else {
    error_log("Warning: Plugin {$plugin_name} not configured correctly");
    exit();
}

if ((count($argv) > 1) && ($argv[1] == 'config')) {
    print("graph_title Players connected to {$host}:{$port}\n");
    print("graph_vlabel players\n");
    print("players.label Number of players\n");
    print("max_players.label Max players\n");
    print("graph_info Number of players connected to Minecraft. " .
    "If Max players is 0, the server is unreachable.\n");
    print("graph_scale no\n");
    print("graph_category minecraft\n");
    exit();
}

/*
  ================
  Server List Ping
  ================

  An example of how to get a Minecraft server status's using a "Server List Ping" packet.
  See details here: http://www.wiki.vg/Server_List_Ping
*/

function MC_packString($string)
{
    $letterCount = strlen($string);
    return pack('n', $letterCount) . mb_convert_encoding($string, 'UTF-16BE');
}

// This is needed since UCS-2 text rendered as UTF-8 contains unnecessary null bytes
// and could cause other components, especially string functions to blow up. Boom!
function MC_decodeUTF16BE($string)
{
    return mb_convert_encoding($string, 'UTF-8', 'UTF-16BE');
}

function MC_serverListPing($hostname, $port)
{
    // 1. pack data to send
    $request = pack('nc', 0xfe01, 0xfa) .
        MC_packString('MC|PingHost') .
        pack('nc', 7+2*strlen($hostname), 73) .
        MC_packString($hostname) .
        pack('N', $port);

    // 2. open communication socket and make transaction
    $time = microtime(true);
    $fp = stream_socket_client('tcp://' . $hostname . ':' . $port);
    stream_set_timeout($fp, 5);
    if (!$fp) {
        return false;
    }

    fwrite($fp, $request);
    $response = fread($fp, 2048);
    $socketInfo = stream_get_meta_data($fp);

    fclose($fp);
    if ($socketInfo['timed_out']) {
      return false;
    }

    $time = round((microtime(true)-$time)*1000);

    // 3. unpack data and return
    if (strpos($response, 0xFF) !== 0) {
        return false;
    }
    $response = substr($response, 3);
    $response = explode(pack('n', 0), $response);

    return array(
        'player_count' => MC_decodeUTF16BE($response[4]),
        'player_max' => MC_decodeUTF16BE($response[5]),
        'motd' => MC_decodeUTF16BE($response[3]),
        'server_version' => MC_decodeUTF16BE($response[2]),
        'protocol_version' => MC_decodeUTF16BE($response[1]),
        'latency' => $time
    );
}

// ============================================================

$reply = MC_serverListPing($host, $port);
$player_count = empty($reply['player_count']) ? '0' : $reply['player_count'];
$player_max = empty($reply['player_max']) ? '0' : $reply['player_max'];

print('players.value ' . $player_count . "\n");
print('max_players.value ' . $player_max . "\n");
?>
